# Generated by Django 5.2.8 on 2025-11-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descritpion',
            new_name='description',
        ),
    ]
